version: '3'

services:
  mysqldb:
    image: mysql:8.0.35
    restart: always
    user: 'mysql:mysql' # for permission issue
    environment:
      MYSQL_DATABASE: SDB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "$PWD/my-db:/var/lib/mysql"
