version: '3'

services:
  mysqldb:
    image: mysql:8.0.35
    restart: always
    user: 'mysql:mysql' # for permission issue
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: $USER
      MYSQL_PASSWORD: $PASSWORD
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "$PWD/my-db:/var/lib/mysql"
